### ISSUE TITLE
Support both != and <> for inequality

### ISSUE THREAD

**Issue by miguel-branco** [raw-db/raw#63]

**Comment by bgaidioz** [comment]
I tried a patch like to see and it looks like it's working. Is there anything I didn't think about?

      "<>" ^^^ Neq() |
      "!=" ^^^ Neq() |  <-------

Should we also have == parsed like = ?

**Comment by miguel-branco** [comment]
I think that's it; except the pretty printer will only take one style but
that's fine.

**Comment by bgaidioz** [comment]
The support of == seems to cause problems. I thought it could be because of =, but the error message was totally unclear. Thus I don't put it.

I'll refresh my mind on how to issue pull requests and commit unless you have a comment.

I take the opportunity to suggest a change below to the pretty printer. To use <> instead of <+> for lambda expressions. One of the test cases was failing because of that. \(a,b) is printed as \ (a,b) (with a space).

--- a/core/src/main/scala/raw/calculus/CalculusPrettyPrinter.scala
+++ b/core/src/main/scala/raw/calculus/CalculusPrettyPrinter.scala
@@ -46,7 +46,7 @@ object CalculusPrettyPrinter extends PrettyPrinter {
       case MergeMonoid(m, e1, e2)     => apply(e1) <+> merge(m) <+> apply(e2)
       case Comp(m, qs, e)             => "for" <+> parens(group(nest(lsep(qs.map(apply), ";")))) <+> "yield" <+> monoid(m) <+> apply(e)
       case UnaryExp(op, e)            => unaryOp(op) <+> apply(e)
-      case FunAbs(idn, e)             => "\\" <+> apply(idn) <+> "->" <+> apply(e)
+      case FunAbs(idn, e)             => "\\" <> apply(idn) <+> "->" <+> apply(e)
       case Gen(idn, e)                => apply(idn) <+> "<-" <+> apply(e)
       case Bind(idn, e)               => apply(idn) <+> ":=" <+> apply(e)
       case ExpBlock(bs, e)            => val ns: Seq[CalculusNode] = bs :+ e; "{" <+> group(nest(lsep(ns.map(apply), ";"))) <+> "}"
@@ -54,7 +54,7 @@ object CalculusPrettyPrinter extends PrettyPrinter {
       case PatternProd(ps)            => parens(group(nest(lsep(ps.map(apply), comma))))
       case PatternBind(p, e)          => apply(p) <+> ":=" <+> apply(e)
       case PatternGen(p, e)           => apply(p) <+> "<-" <+> apply(e)
-      case PatternFunAbs(p, e)        => "\\" <+> apply(p) <+> "->" <+> apply(e)
+      case PatternFunAbs(p, e)        => "\\" <> apply(p) <+> "->" <+> apply(e)
     })




________________________________
